package cn.ljf.time.model;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ACTIVITY.ACT_ID
     *
     * @mbggenerated
     */
    private String actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ACTIVITY.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ACTIVITY.ACT_TIME
     *
     * @mbggenerated
     */
    private Date actTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ACTIVITY.ACT_CONTENT
     *
     * @mbggenerated
     */
    private String actContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ACTIVITY.ACT_ID
     *
     * @return the value of TB_ACTIVITY.ACT_ID
     *
     * @mbggenerated
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ACTIVITY.ACT_ID
     *
     * @param actId the value for TB_ACTIVITY.ACT_ID
     *
     * @mbggenerated
     */
    public void setActId(String actId) {
        this.actId = actId == null ? null : actId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ACTIVITY.TITLE
     *
     * @return the value of TB_ACTIVITY.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ACTIVITY.TITLE
     *
     * @param title the value for TB_ACTIVITY.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ACTIVITY.ACT_TIME
     *
     * @return the value of TB_ACTIVITY.ACT_TIME
     *
     * @mbggenerated
     */
    public Date getActTime() {
        return actTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ACTIVITY.ACT_TIME
     *
     * @param actTime the value for TB_ACTIVITY.ACT_TIME
     *
     * @mbggenerated
     */
    public void setActTime(Date actTime) {
        this.actTime = actTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ACTIVITY.ACT_CONTENT
     *
     * @return the value of TB_ACTIVITY.ACT_CONTENT
     *
     * @mbggenerated
     */
    public String getActContent() {
        return actContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ACTIVITY.ACT_CONTENT
     *
     * @param actContent the value for TB_ACTIVITY.ACT_CONTENT
     *
     * @mbggenerated
     */
    public void setActContent(String actContent) {
        this.actContent = actContent == null ? null : actContent.trim();
    }
}