package cn.ljf.time.model;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AREA.AREA_ID
     *
     * @mbggenerated
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AREA.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AREA.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AREA.DISTRICT
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AREA.AREA_ID
     *
     * @return the value of TB_AREA.AREA_ID
     *
     * @mbggenerated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AREA.AREA_ID
     *
     * @param areaId the value for TB_AREA.AREA_ID
     *
     * @mbggenerated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AREA.PROVINCE
     *
     * @return the value of TB_AREA.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AREA.PROVINCE
     *
     * @param province the value for TB_AREA.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AREA.CITY
     *
     * @return the value of TB_AREA.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AREA.CITY
     *
     * @param city the value for TB_AREA.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AREA.DISTRICT
     *
     * @return the value of TB_AREA.DISTRICT
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AREA.DISTRICT
     *
     * @param district the value for TB_AREA.DISTRICT
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }
}