package cn.ljf.time.model;

public class Permissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PERMISSIONS.PER_ID
     *
     * @mbggenerated
     */
    private String perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PERMISSIONS.FATHER_ID
     *
     * @mbggenerated
     */
    private String fatherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PERMISSIONS.PER_NAME
     *
     * @mbggenerated
     */
    private String perName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PERMISSIONS.PER_DESC
     *
     * @mbggenerated
     */
    private String perDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PERMISSIONS.PER_ID
     *
     * @return the value of TB_PERMISSIONS.PER_ID
     *
     * @mbggenerated
     */
    public String getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PERMISSIONS.PER_ID
     *
     * @param perId the value for TB_PERMISSIONS.PER_ID
     *
     * @mbggenerated
     */
    public void setPerId(String perId) {
        this.perId = perId == null ? null : perId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PERMISSIONS.FATHER_ID
     *
     * @return the value of TB_PERMISSIONS.FATHER_ID
     *
     * @mbggenerated
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PERMISSIONS.FATHER_ID
     *
     * @param fatherId the value for TB_PERMISSIONS.FATHER_ID
     *
     * @mbggenerated
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId == null ? null : fatherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PERMISSIONS.PER_NAME
     *
     * @return the value of TB_PERMISSIONS.PER_NAME
     *
     * @mbggenerated
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PERMISSIONS.PER_NAME
     *
     * @param perName the value for TB_PERMISSIONS.PER_NAME
     *
     * @mbggenerated
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_PERMISSIONS.PER_DESC
     *
     * @return the value of TB_PERMISSIONS.PER_DESC
     *
     * @mbggenerated
     */
    public String getPerDesc() {
        return perDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_PERMISSIONS.PER_DESC
     *
     * @param perDesc the value for TB_PERMISSIONS.PER_DESC
     *
     * @mbggenerated
     */
    public void setPerDesc(String perDesc) {
        this.perDesc = perDesc == null ? null : perDesc.trim();
    }
}