package cn.ljf.time.model;

import java.math.BigDecimal;
import java.util.Date;

public class User {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.USER_ID
     *
     * @mbggenerated
     */
    private String userId;
    private BigDecimal areaId;
    private String email;
    private String avatarFile;
    private Date registerDate;
    private String remark;
    private String username;
    private String userPassword;
    private String permissions;
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.USER_ID
     *
     * @return the value of TB_USER.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.USER_ID
     *
     * @param userId the value for TB_USER.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.AREA_ID
     *
     * @return the value of TB_USER.AREA_ID
     *
     * @mbggenerated
     */
    public BigDecimal getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.AREA_ID
     *
     * @param areaId the value for TB_USER.AREA_ID
     *
     * @mbggenerated
     */
    public void setAreaId(BigDecimal areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.EMAIL
     *
     * @return the value of TB_USER.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.EMAIL
     *
     * @param email the value for TB_USER.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.AVATAR_FILE
     *
     * @return the value of TB_USER.AVATAR_FILE
     *
     * @mbggenerated
     */
    public String getAvatarFile() {
        return avatarFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.AVATAR_FILE
     *
     * @param avatarFile the value for TB_USER.AVATAR_FILE
     *
     * @mbggenerated
     */
    public void setAvatarFile(String avatarFile) {
        this.avatarFile = avatarFile == null ? null : avatarFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.REGISTER_DATE
     *
     * @return the value of TB_USER.REGISTER_DATE
     *
     * @mbggenerated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.REGISTER_DATE
     *
     * @param registerDate the value for TB_USER.REGISTER_DATE
     *
     * @mbggenerated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.REMARK
     *
     * @return the value of TB_USER.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.REMARK
     *
     * @param remark the value for TB_USER.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.USERNAME
     *
     * @return the value of TB_USER.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.USERNAME
     *
     * @param username the value for TB_USER.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.USER_PASSWORD
     *
     * @return the value of TB_USER.USER_PASSWORD
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.USER_PASSWORD
     *
     * @param userPassword the value for TB_USER.USER_PASSWORD
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.PERMISSIONS
     *
     * @return the value of TB_USER.PERMISSIONS
     *
     * @mbggenerated
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.PERMISSIONS
     *
     * @param permissions the value for TB_USER.PERMISSIONS
     *
     * @mbggenerated
     */
    public void setPermissions(String permissions) {
        this.permissions = permissions == null ? null : permissions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.ROLENAME
     *
     * @return the value of TB_USER.ROLENAME
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.ROLENAME
     *
     * @param rolename the value for TB_USER.ROLENAME
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }
    @Override
    public String toString() {
        return "User{" +
                "userId='" + userId + '\'' +
                ", areaId=" + areaId +
                ", email='" + email + '\'' +
                ", avatarFile='" + avatarFile + '\'' +
                ", registerDate=" + registerDate +
                ", remark='" + remark + '\'' +
                ", username='" + username + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", permissions='" + permissions + '\'' +
                ", rolename='" + rolename + '\'' +
                '}';
    }
}