package cn.ljf.time.dao;

import cn.ljf.time.model.Activity;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ACTIVITY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ACTIVITY
     *
     * @mbggenerated
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ACTIVITY
     *
     * @mbggenerated
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ACTIVITY
     *
     * @mbggenerated
     */
    Activity selectByPrimaryKey(String actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ACTIVITY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ACTIVITY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Activity record);
}