package cn.ljf.time.dao;

import cn.ljf.time.model.Area;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AREA
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AREA
     *
     * @mbggenerated
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AREA
     *
     * @mbggenerated
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AREA
     *
     * @mbggenerated
     */
    Area selectByPrimaryKey(String areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AREA
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AREA
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Area record);
}