package cn.ljf.time.dao;

import cn.ljf.time.model.CalendarEvent;

public interface CalendarEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CALENDAR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String calId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CALENDAR
     *
     * @mbggenerated
     */
    int insert(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CALENDAR
     *
     * @mbggenerated
     */
    int insertSelective(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CALENDAR
     *
     * @mbggenerated
     */
    CalendarEvent selectByPrimaryKey(String calId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CALENDAR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CALENDAR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CalendarEvent record);
}