package cn.ljf.time.dao;

import cn.ljf.time.model.Diary;

public interface DiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DIARY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DIARY
     *
     * @mbggenerated
     */
    int insert(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DIARY
     *
     * @mbggenerated
     */
    int insertSelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DIARY
     *
     * @mbggenerated
     */
    Diary selectByPrimaryKey(String diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DIARY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_DIARY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Diary record);
}