package cn.ljf.time.dao;

import cn.ljf.time.model.Permissions;

public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PERMISSIONS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PERMISSIONS
     *
     * @mbggenerated
     */
    int insert(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PERMISSIONS
     *
     * @mbggenerated
     */
    int insertSelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PERMISSIONS
     *
     * @mbggenerated
     */
    Permissions selectByPrimaryKey(String perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PERMISSIONS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PERMISSIONS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Permissions record);
}